/* ============================================
   NeuralKSP — Automated Intelligence Briefing Engine
   Interactive Operational Reports for Police Leadership
   ============================================ */

(function() {
    'use strict';

    const BriefingModule = {
        _initialized: false,
        activeTab: 'overview',

        init: function() {
            this.bindEvents();
            this.populateControls();
            this.generateBriefing();
            this._initialized = true;
        },

        bindEvents: function() {
            const generateBtn = document.getElementById('generate-briefing');
            const exportBtn = document.getElementById('export-briefing');

            if (generateBtn) {
                generateBtn.onclick = () => this.generateBriefing();
            }
            if (exportBtn) {
                exportBtn.onclick = () => window.print();
            }
        },

        populateControls: function() {
            const stationSelect = document.getElementById('briefing-station');
            const dateInput = document.getElementById('briefing-date');

            if (stationSelect && window.NeuralKSP && window.NeuralKSP.data) {
                const stations = window.NeuralKSP.data.stations || [];
                let html = '<option value="all">All Stations (Statewide)</option>';
                stations.forEach(st => {
                    html += `<option value="${st}">${st}</option>`;
                });
                stationSelect.innerHTML = html;
            }

            if (dateInput && !dateInput.value) {
                dateInput.value = new Date().toISOString().split('T')[0];
            }
        },        generateBriefing: function() {
            const contentDiv = document.getElementById('briefing-content');
            if (!contentDiv) return;

            const station = document.getElementById('briefing-station')?.value || 'all';
            const date = document.getElementById('briefing-date')?.value || new Date().toISOString().split('T')[0];
            const data = window.NeuralKSP?.data;

            if (!data) {
                contentDiv.innerHTML = '<div class="glass-card" style="padding:20px; color:var(--accent-red);">Error: NeuralKSP data engine not loaded.</div>';
                return;
            }

            const isKn = window.NeuralKSPApp && window.NeuralKSPApp.language === 'kn';

            // Filter incidents by station
            let incidents = data.crimes || [];
            if (station !== 'all') {
                incidents = incidents.filter(i => i.station === station);
            }

            const totalIncidents = incidents.length;
            const activeCases = incidents.filter(i => i.status !== 'Closed').length;
            const solvedCases = totalIncidents - activeCases;
            const clearanceRate = totalIncidents > 0 ? Math.round((solvedCases / totalIncidents) * 100) : 0;
            const highRiskIncidents = incidents.filter(i => i.severity === 'High').length;

            // Group crimes by category
            const categoryCounts = {};
            incidents.forEach(i => {
                const cat = i.category || 'Other';
                categoryCounts[cat] = (categoryCounts[cat] || 0) + 1;
            });

            // Filter high-risk accused for watchlist
            const accusedList = data.accused || [];
            const highRiskAccused = [...accusedList]
                .sort((a, b) => b.riskScore - a.riskScore)
                .slice(0, 4);

            const isLight = document.body.classList.contains('light-theme');

            const confidentialTag = isKn ? '🛡️ ರಹಸ್ಯ — ಕರ್ನಾಟಕ ಪೊಲೀಸ್ ಆಂತರಿಕ ಬಳಕೆಗೆ ಮಾತ್ರ' : '🛡️ CONFIDENTIAL — KARNATAKA POLICE INTERNAL USE ONLY';
            const docTitle = isKn ? 'ದೈನಂದಿನ ಕಾರ್ಯಾಚರಣೆಯ ಗುಪ್ತಚರ ವರದಿ' : 'Daily Operational Intelligence Briefing';
            const scopeLabel = isKn ? 'ಅಧಿಕಾರ ವ್ಯಾಪ್ತಿ:' : 'Jurisdiction Scope:';
            const allStationsText = isKn ? 'ಎಲ್ಲಾ ಠಾಣೆಗಳು (ರಾಜ್ಯವ್ಯಾಪಿ ಕಮಾಂಡ್)' : 'All Stations (Statewide Command)';
            const targetDateLabel = isKn ? 'ಗುರಿ ದಿನಾಂಕ:' : 'Target Date:';
            const generatedByText = isKn ? 'ನ್ಯೂರಲ್-ಕೆಎಸ್‌ಪಿ ಎಐ ಮೂಲಕ ರಚಿಸಲಾಗಿದೆ' : 'Generated by NeuralKSP AI';

            // Tabs
            const tabOverview = isKn ? '📊 ಕಾರ್ಯನಿರ್ವಾಹಕ ಸಾರಾಂಶ' : '📊 Executive Summary';
            const tabThreats = isKn ? '⚠️ ಅಸಂಗತತೆ ಬೆದರಿಕೆ ಎಚ್ಚರಿಕೆಗಳು' : '⚠️ Anomaly Threat Alerts';
            const tabPatrol = isKn ? '🚓 ಪಟ್ರೋಲಿಂಗ್ ನಿಯೋಜನೆ ನಿರ್ದೇಶನಗಳು' : '🚓 Patrol Deployment Directives';
            const tabWatchlist = isKn ? '🎯 ಆದ್ಯತೆಯ ಶಂಕಿತರ ವೀಕ್ಷಣೆ ಪಟ್ಟಿ' : '🎯 Priority Target Watchlist';

            // Overview KPIs
            const kpiTotal = isKn ? 'ಒಟ್ಟು ಎಫ್‌ಐಆರ್ ಘಟನೆಗಳು' : 'Total FIR Incidents';
            const kpiTotalSub = isKn ? 'ವ್ಯಾಪ್ತಿಯಲ್ಲಿನ ನೋಂದಾಯಿತ ಪ್ರಕರಣಗಳು' : 'Registered cases in scope';
            const kpiActive = isKn ? 'ಸಕ್ರಿಯ ತನಿಖಾ ಪ್ರಕರಣಗಳು' : 'Active Investigation Cases';
            const kpiActiveSub = isKn ? 'ಚಾರ್ಜ್-ಶೀಟ್ ಸಲ್ಲಿಕೆ ಬಾಕಿ' : 'Pending charge-sheet filing';
            const kpiClearance = isKn ? 'ಪ್ರಕರಣ ವಿಲೇವಾರಿ ದರ' : 'Case Clearance Rate';
            const kpiClearanceSub = isKn ? 'ಪರಿಹರಿಸಿದ ಪ್ರಕರಣಗಳ ಅನುಪಾತ' : 'Solved vs Registered ratio';
            const kpiHigh = isKn ? 'ಹೆಚ್ಚಿನ ಗಂಭೀರತೆಯ ಅಪರಾಧಗಳು' : 'High-Severity Crimes';
            const kpiHighSub = isKn ? 'ತಕ್ಷಣದ ಎಸ್‌ಪಿ ಪರಿಶೀಲನೆ ಅಗತ್ಯ' : 'Requires immediate SP review';

            // Table
            const tblTitle = isKn ? 'ವರ್ಗವಾರು ಅಪರಾಧ ವಿವರಣೆ' : 'Crime Breakdown by Category';
            const thCat = isKn ? 'ವರ್ಗ' : 'Category';
            const thCount = isKn ? 'ಪ್ರಕರಣ ಸಂಖ್ಯೆ' : 'Incident Count';
            const thShare = isKn ? 'ಪಾಲು %' : 'Share';
            const thRisk = isKn ? 'ಅಪಾಯದ ಮಟ್ಟ' : 'Risk Level';

            // Threats
            const threatTitle = isKn ? 'ಸಕ್ರಿಯ ಎಐ-ಪತ್ತೆ ಮಾಡಿದ ಅಪರಾಧ ಅಸಂಗತತೆಗಳು' : 'Active AI-Detected Crime Anomalies';

            // Patrol
            const patrolTitle = isKn ? 'ಶಿಫಾರಸು ಮಾಡಿದ ಪೊಲೀಸ್ ಪಡೆ ಮತ್ತು ಪಟ್ರೋಲಿಂಗ್ ನಿಯೋಜನೆಗಳು' : 'Recommended Force & Patrol Deployments';
            const sec1Name = isKn ? 'ರಾತ್ರಿ ಶಿಫ್ಟ್ ಸೆಕ್ಟರ್ 1' : 'Night Shift Sector 1';
            const sec1Loc = isKn ? 'ಕೋರಮಂಗಲ 80 ಅಡಿ ರಸ್ತೆ ಮತ್ತು ರಿಂಗ್ ರಸ್ತೆ' : 'Koramangala 80ft Road & Outer Ring Rd';
            const sec1Time = isKn ? 'ಗರಿಷ್ಠ ಸಮಯ: ರಾತ್ರಿ 8:00 – 11:00' : 'Peak Window: 8:00 PM – 11:00 PM';
            const sec1Force = isKn ? 'ಶಿಫಾರಸು ಮಾಡಿದ ಪಡೆ: 2 ಹೊಯ್ಸಳ ಪಟ್ರೋಲ್ + 4 ಬೀಟ್ ಕಾನ್‌ಸ್ಟೇಬಲ್‌ಗಳು' : 'Recommended Force: 2 Patrol Hoysalas + 4 Beat Constables (Anti-chain snatching)';

            const sec2Name = isKn ? 'ರಾತ್ರಿ ಶಿಫ್ಟ್ ಸೆಕ್ಟರ್ 2' : 'Night Shift Sector 2';
            const sec2Loc = isKn ? 'ಎಲೆಕ್ಟ್ರಾನಿಕ್ ಸಿಟಿ ಫೇಸ್ 1 ಐಟಿ ಕಾರಿಡಾರ್' : 'Electronic City Phase 1 IT Corridor';
            const sec2Time = isKn ? 'ಗರಿಷ್ಠ ಸಮಯ: ರಾತ್ರಿ 10:00 – 1:00' : 'Peak Window: 10:00 PM – 1:00 AM';
            const sec2Force = isKn ? 'ಶಿಫಾರಸು ಮಾಡಿದ ಪಡೆ: 3 ವಾಹನ ತಪಾಸಣೆ ಕೇಂದ್ರಗಳು + ಪಿಸಿಆರ್ ವ್ಯಾನ್' : 'Recommended Force: 3 Vehicle Checkpoints + Mobile PCR Van (Vehicle Theft Control)';

            const sec3Name = isKn ? 'ಹಗಲು ಶಿಫ್ಟ್ ಸೆಕ್ಟರ್ 3' : 'Day Shift Sector 3';
            const sec3Loc = isKn ? 'ಜಯನಗರ 4ನೇ ಬ್ಲಾಕ್ ವಾಣಿಜ್ಯ ಸಂಕೀರ್ಣ' : 'Jayanagar 4th Block Commercial Hub';
            const sec3Time = isKn ? 'ಗರಿಷ್ಠ ಸಮಯ: ಮಧ್ಯಾಹ್ನ 2:00 – 5:00' : 'Peak Window: 2:00 PM – 5:00 PM';
            const sec3Force = isKn ? 'ಶಿಫಾರಸು ಮಾಡಿದ ಪಡೆ: ಕಾಲ್ನಡಿಗೆ ಪಟ್ರೋಲಿಂಗ್ + ಸೈಬರ್ ಜಾಗೃತಿ ಕೇಂದ್ರ' : 'Recommended Force: Foot Patrols + Cyber Fraud Awareness Kiosk';

            // Watchlist
            const watchTitle = isKn ? 'ಕಣ್ಗಾವಲು ಅಗತ್ಯವಿರುವ ಆದ್ಯತೆಯ ಶಂಕಿತರ ಪಟ್ಟಿ' : 'Priority Target Suspect Watchlist';

            let html = `
                <!-- Official Karnataka Police Document Header -->
                <div class="glass-card" style="padding:24px; margin-bottom:20px; border-top:4px solid var(--accent-cyan); position:relative; overflow:hidden;">
                    <div style="display:flex; justify-content:space-between; align-items:flex-start; flex-wrap:wrap; gap:16px;">
                        <div>
                            <div style="display:inline-block; padding:4px 12px; background:rgba(239,68,68,0.15); border:1px solid #ef4444; border-radius:4px; color:#ef4444; font-weight:800; font-size:0.75rem; tracking-wider:1px; margin-bottom:8px;">
                                ${confidentialTag}
                            </div>
                            <h2 style="font-size:1.6rem; font-weight:800; color:var(--text-primary); margin:0;">${docTitle}</h2>
                            <div style="font-size:0.9rem; color:var(--text-secondary); margin-top:4px;">
                                ${scopeLabel} <strong style="color:var(--accent-cyan);">${station === 'all' ? allStationsText : station}</strong> | ${targetDateLabel} <strong>${date}</strong>
                            </div>
                        </div>
                        <div style="text-align:right;">
                            <div style="font-size:0.75rem; color:var(--text-muted);">${generatedByText}</div>
                            <div style="font-size:0.85rem; font-weight:700; color:var(--text-primary);">${new Date().toLocaleTimeString()} IST</div>
                        </div>
                    </div>

                    <!-- Interactive Briefing Tabs -->
                    <div style="display:flex; gap:12px; margin-top:20px; border-bottom:1px solid var(--border-subtle); padding-bottom:12px; flex-wrap:wrap;">
                        <button class="btn ${this.activeTab === 'overview' ? 'btn-primary' : 'btn-secondary'}" onclick="window.BriefingModule.switchTab('overview')">
                            ${tabOverview}
                        </button>
                        <button class="btn ${this.activeTab === 'threats' ? 'btn-primary' : 'btn-secondary'}" onclick="window.BriefingModule.switchTab('threats')">
                            ${tabThreats}
                        </button>
                        <button class="btn ${this.activeTab === 'patrol' ? 'btn-primary' : 'btn-secondary'}" onclick="window.BriefingModule.switchTab('patrol')">
                            ${tabPatrol}
                        </button>
                        <button class="btn ${this.activeTab === 'watchlist' ? 'btn-primary' : 'btn-secondary'}" onclick="window.BriefingModule.switchTab('watchlist')">
                            ${tabWatchlist}
                        </button>
                    </div>
                </div>

                <!-- TAB CONTENT CONTAINER -->
                <div id="briefing-tab-content">
            `;

            if (this.activeTab === 'overview') {
                html += `
                    <!-- Executive Summary KPI Cards -->
                    <div style="display:grid; grid-template-columns:repeat(auto-fit, minmax(220px, 1fr)); gap:16px; margin-bottom:20px;">
                        <div class="glass-card stat-card" style="padding:16px; border-top:4px solid var(--accent-cyan);">
                            <div style="font-size:0.75rem; color:var(--text-muted); text-transform:uppercase; font-weight:700;">${kpiTotal}</div>
                            <div style="font-size:2rem; font-weight:800; color:var(--accent-cyan); margin-top:4px;">${totalIncidents}</div>
                            <div style="font-size:0.75rem; color:var(--text-secondary); margin-top:4px;">${kpiTotalSub}</div>
                        </div>
                        <div class="glass-card stat-card" style="padding:16px; border-top:4px solid var(--accent-red);">
                            <div style="font-size:0.75rem; color:var(--text-muted); text-transform:uppercase; font-weight:700;">${kpiActive}</div>
                            <div style="font-size:2rem; font-weight:800; color:var(--accent-red); margin-top:4px;">${activeCases}</div>
                            <div style="font-size:0.75rem; color:var(--text-secondary); margin-top:4px;">${kpiActiveSub}</div>
                        </div>
                        <div class="glass-card stat-card" style="padding:16px; border-top:4px solid var(--accent-green);">
                            <div style="font-size:0.75rem; color:var(--text-muted); text-transform:uppercase; font-weight:700;">${kpiClearance}</div>
                            <div style="font-size:2rem; font-weight:800; color:var(--accent-green); margin-top:4px;">${clearanceRate}%</div>
                            <div style="font-size:0.75rem; color:var(--text-secondary); margin-top:4px;">${kpiClearanceSub}</div>
                        </div>
                        <div class="glass-card stat-card" style="padding:16px; border-top:4px solid var(--accent-amber);">
                            <div style="font-size:0.75rem; color:var(--text-muted); text-transform:uppercase; font-weight:700;">${kpiHigh}</div>
                            <div style="font-size:2rem; font-weight:800; color:var(--accent-amber); margin-top:4px;">${highRiskIncidents}</div>
                            <div style="font-size:0.75rem; color:var(--text-secondary); margin-top:4px;">${kpiHighSub}</div>
                        </div>
                    </div>

                    <!-- Crime Category Distribution Table -->
                    <div class="glass-card" style="padding:20px; margin-bottom:20px;">
                        <h3 style="font-size:1.1rem; font-weight:800; color:var(--text-primary); margin:0 0 16px 0;">${tblTitle}</h3>
                        <div style="overflow-x:auto;">
                            <table style="width:100%; border-collapse:collapse; text-align:left; font-size:0.85rem;">
                                <thead>
                                    <tr style="border-bottom:2px solid var(--border-subtle); color:var(--text-muted);">
                                        <th style="padding:10px;">${thCat}</th>
                                        <th style="padding:10px;">${thCount}</th>
                                        <th style="padding:10px;">${thShare}</th>
                                        <th style="padding:10px;">${thRisk}</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    ${Object.keys(categoryCounts).map(cat => {
                                        const count = categoryCounts[cat];
                                        const pct = Math.round((count / totalIncidents) * 100) || 0;
                                        const riskTag = pct > 25 ? `<span style="color:var(--accent-red); font-weight:700;">${isKn ? 'ಹೆಚ್ಚು' : 'High'}</span>` : `<span style="color:var(--accent-green); font-weight:700;">${isKn ? 'ಮಧ್ಯಮ' : 'Moderate'}</span>`;
                                        const catName = isKn ? (cat === 'Property Crime' ? 'ಆಸ್ತಿ ಅಪರಾಧಗಳು' : cat === 'Violent' ? 'ಹಿಂಸಾತ್ಮಕ' : cat === 'Economic Offence' ? 'ಆರ್ಥಿಕ ಅಪರಾಧ' : cat === 'Cyber' ? 'ಸೈಬರ್ ಅಪರಾಧ' : cat === 'Traffic' ? 'ಸಂಚಾರ ನಿಯಮ' : cat) : cat;
                                        return `
                                            <tr style="border-bottom:1px solid var(--border-subtle); color:var(--text-primary);">
                                                <td style="padding:10px; font-weight:700;">${catName}</td>
                                                <td style="padding:10px; color:var(--accent-cyan); font-weight:800;">${count}</td>
                                                <td style="padding:10px;">${pct}%</td>
                                                <td style="padding:10px;">${riskTag}</td>
                                            </tr>
                                        `;
                                    }).join('')}
                                </tbody>
                            </table>
                        </div>
                    </div>
                `;
            } else if (this.activeTab === 'threats') {
                const anomalies = data.anomalies || [];
                html += `
                    <div class="glass-card" style="padding:20px; margin-bottom:20px;">
                        <h3 style="font-size:1.1rem; font-weight:800; color:var(--text-primary); margin:0 0 16px 0;">${threatTitle}</h3>
                        ${anomalies.map(a => {
                            let title = a.title;
                            let desc = a.description;
                            if (isKn) {
                                if (title.includes('Syndicate')) {
                                    title = 'ಬೆಂಗಳೂರು ನಗರದಲ್ಲಿ ಹೊಸ ಗ್ಯಾಂಗ್ ಪತ್ತೆಯಾಗಿದೆ';
                                    desc = 'ಕಳೆದ 30 ದಿನಗಳಲ್ಲಿ 3 ಎಫ್‌ಐಆರ್‌ಗಳ ಮೂಲಕ 5 ಆರೋಪಿಗಳು ಸಂಪರ್ಕ ಹೊಂದಿದ್ದಾರೆ.';
                                } else if (title.includes('Surge')) {
                                    title = 'ಮೈಸೂರಿನಲ್ಲಿ ಸೈಬರ್ ಅಪರಾಧಗಳ ಹೆಚ್ಚಳ';
                                    desc = 'ಈ ತಿಂಗಳಲ್ಲಿ ಮಾಹಿತಿ ತಂತ್ರಜ್ಞಾನ ಕಾಯ್ದೆಯಡಿ ಶೇ.42 ರಷ್ಟು ಪ್ರಕರಣಗಳು ಹೆಚ್ಚಾಗಿವೆ.';
                                } else if (title.includes('Theft')) {
                                    title = 'ಎಲೆಕ್ಟ್ರಾನಿಕ್ ಸಿಟಿಯಲ್ಲಿ ವಾಹನ ಕಳವು';
                                    desc = 'ಕಳೆದ 7 ದಿನಗಳಲ್ಲಿ 2 ಕಿಮೀ ವ್ಯಾಪ್ತಿಯಲ್ಲಿ 8 ವಾಹನ ಕಳವು ವರದಿಯಾಗಿದೆ.';
                                }
                            }
                            return `
                                <div style="padding:16px; margin-bottom:12px; background:rgba(239,68,68,0.08); border-left:4px solid var(--accent-red); border-radius:8px;">
                                    <div style="display:flex; justify-content:space-between; align-items:flex-start;">
                                        <h4 style="font-size:1rem; font-weight:800; color:var(--text-primary); margin:0;">${title}</h4>
                                        <span style="background:var(--accent-red); color:#fff; padding:2px 8px; border-radius:12px; font-size:0.75rem; font-weight:800;">Z-Score: ${a.zScore}</span>
                                    </div>
                                    <p style="font-size:0.85rem; color:var(--text-secondary); margin:8px 0 0 0;">${desc}</p>
                                    <div style="font-size:0.75rem; color:var(--text-muted); margin-top:6px;">
                                        ${isKn ? 'ಅಧಿಕಾರ ವ್ಯಾಪ್ತಿ' : 'Jurisdiction'}: <strong>${a.district}</strong> • ${isKn ? 'ಪತ್ತೆಯಾದ ಸಮಯ' : 'Time Detected'}: <strong>${new Date(a.timestamp).toLocaleTimeString()} IST</strong>
                                    </div>
                                </div>
                            `;
                        }).join('')}
                    </div>
                `;
            } else if (this.activeTab === 'patrol') {
                html += `
                    <div class="glass-card" style="padding:20px; margin-bottom:20px;">
                        <h3 style="font-size:1.1rem; font-weight:800; color:var(--text-primary); margin:0 0 16px 0;">${patrolTitle}</h3>
                        <div style="display:grid; grid-template-columns:repeat(auto-fit, minmax(280px, 1fr)); gap:16px;">
                            <div style="padding:16px; background:var(--bg-tertiary); border-radius:8px; border-left:4px solid var(--accent-amber);">
                                <div style="font-size:0.75rem; color:var(--text-muted); uppercase; font-weight:700;">${sec1Name}</div>
                                <div style="font-size:1rem; font-weight:800; color:var(--text-primary); margin-top:4px;">${sec1Loc}</div>
                                <div style="font-size:0.85rem; color:var(--accent-cyan); font-weight:700; margin-top:4px;">${sec1Time}</div>
                                <div style="font-size:0.8rem; color:var(--text-secondary); margin-top:6px;">${sec1Force}</div>
                            </div>
                            <div style="padding:16px; background:var(--bg-tertiary); border-radius:8px; border-left:4px solid var(--accent-red);">
                                <div style="font-size:0.75rem; color:var(--text-muted); uppercase; font-weight:700;">${sec2Name}</div>
                                <div style="font-size:1rem; font-weight:800; color:var(--text-primary); margin-top:4px;">${sec2Loc}</div>
                                <div style="font-size:0.85rem; color:var(--accent-cyan); font-weight:700; margin-top:4px;">${sec2Time}</div>
                                <div style="font-size:0.8rem; color:var(--text-secondary); margin-top:6px;">${sec2Force}</div>
                            </div>
                            <div style="padding:16px; background:var(--bg-tertiary); border-radius:8px; border-left:4px solid var(--accent-green);">
                                <div style="font-size:0.75rem; color:var(--text-muted); uppercase; font-weight:700;">${sec3Name}</div>
                                <div style="font-size:1rem; font-weight:800; color:var(--text-primary); margin-top:4px;">${sec3Loc}</div>
                                <div style="font-size:0.85rem; color:var(--accent-cyan); font-weight:700; margin-top:4px;">${sec3Time}</div>
                                <div style="font-size:0.8rem; color:var(--text-secondary); margin-top:6px;">${sec3Force}</div>
                            </div>
                        </div>
                    </div>
                `;
            } else if (this.activeTab === 'watchlist') {
                const getKnName = (name) => window.NetworkModule && window.NetworkModule.getName ? window.NetworkModule.getName(name) : name;
                const getKnDist = (dist) => window.NetworkModule && window.NetworkModule.getDistrict ? window.NetworkModule.getDistrict(dist) : dist;

                html += `
                    <div class="glass-card" style="padding:20px; margin-bottom:20px;">
                        <h3 style="font-size:1.1rem; font-weight:800; color:var(--text-primary); margin:0 0 16px 0;">${watchTitle}</h3>
                        <div style="display:grid; grid-template-columns:repeat(auto-fit, minmax(280px, 1fr)); gap:16px;">
                            ${highRiskAccused.map(acc => `
                                <div style="padding:16px; background:var(--bg-tertiary); border:1px solid var(--border-subtle); border-radius:8px; display:flex; gap:14px; align-items:center;">
                                    <div style="background:var(--accent-red)22; color:var(--accent-red); font-size:1.5rem; font-weight:800; width:48px; height:48px; border-radius:50%; display:flex; align-items:center; justify-content:center; border:2px solid var(--accent-red);">
                                        ${acc.name.charAt(0)}
                                    </div>
                                    <div>
                                        <div style="font-size:1rem; font-weight:800; color:var(--text-primary);">${getKnName(acc.name)}</div>
                                        <div style="font-size:0.75rem; color:var(--text-muted);">${acc.gender === 'Female' ? (isKn ? 'ಮಹಿಳೆ' : 'Female') : (isKn ? 'ಪುರುಷ' : 'Male')}, ${acc.age} ${isKn ? 'ವರ್ಷ' : 'yrs'} • ${getKnDist(acc.district)}</div>
                                        <div style="font-size:0.8rem; color:var(--accent-red); font-weight:800; margin-top:4px;">
                                            ${isKn ? 'ಅಪಾಯದ ಅಂಕ' : 'Risk Score'}: ${acc.riskScore}/100 • ${acc.priorOffenses} ${isKn ? 'ಎಫ್‌ಐಆರ್‌ಗಳು' : 'FIRs'}
                                        </div>
                                    </div>
                                </div>
                            `).join('')}
                        </div>
                    </div>
                `;
            }

            html += `</div>`;
            contentDiv.innerHTML = html;
        },

        switchTab: function(tabName) {
            this.activeTab = tabName;
            this.generateBriefing();
        }
    };

    window.BriefingModule = BriefingModule;
})();
